env:
  browser: true
  es2020: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules: {
  react/jsx-filename-extension: 0,
  react/jsx-one-expression-per-line: 0
}
